from crypto.ec import Curve, Point

CURVES = {
    # See https://en.bitcoin.it/wiki/Secp256k1 for these domain parameters
    "secp256k1": {
        "generator": (
            0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,  # x coordinate
            0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8,  # y coordinate
        ),
        "a": 0,
        "b": 7,
        # Order of the subgroup generated by the generator.
        "order": 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141,
        # 2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 - 1
        "modulus": 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F,
    }
}


def get_curve(name: str) -> Curve:
    if name not in CURVES:
        raise ValueError(f"Curve {name} not supported")

    params = CURVES[name]
    curve = Curve(params["a"], params["b"], params["modulus"], q=params["order"])
    generator = Point(
        x=params["generator"][0],
        y=params["generator"][1],
        curve=curve,
    )
    curve.generator = generator

    return curve
